/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const AuthenticatedLayoutLazyImport = createFileRoute(
  '/_authenticated-layout',
)()
const IndexLazyImport = createFileRoute('/')()
const SigninIndexLazyImport = createFileRoute('/signin/')()
const AuthenticatedLayoutBrowseIndexLazyImport = createFileRoute(
  '/_authenticated-layout/browse/',
)()

// Create/Update Routes

const AuthenticatedLayoutLazyRoute = AuthenticatedLayoutLazyImport.update({
  id: '/_authenticated-layout',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/_authenticated-layout.lazy').then((d) => d.Route),
)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const SigninIndexLazyRoute = SigninIndexLazyImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signin/index.lazy').then((d) => d.Route))

const AuthenticatedLayoutBrowseIndexLazyRoute =
  AuthenticatedLayoutBrowseIndexLazyImport.update({
    id: '/browse/',
    path: '/browse/',
    getParentRoute: () => AuthenticatedLayoutLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated-layout/browse/index.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated-layout': {
      id: '/_authenticated-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedLayoutLazyImport
      parentRoute: typeof rootRoute
    }
    '/signin/': {
      id: '/signin/'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated-layout/browse/': {
      id: '/_authenticated-layout/browse/'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof AuthenticatedLayoutBrowseIndexLazyImport
      parentRoute: typeof AuthenticatedLayoutLazyImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedLayoutLazyRouteChildren {
  AuthenticatedLayoutBrowseIndexLazyRoute: typeof AuthenticatedLayoutBrowseIndexLazyRoute
}

const AuthenticatedLayoutLazyRouteChildren: AuthenticatedLayoutLazyRouteChildren =
  {
    AuthenticatedLayoutBrowseIndexLazyRoute:
      AuthenticatedLayoutBrowseIndexLazyRoute,
  }

const AuthenticatedLayoutLazyRouteWithChildren =
  AuthenticatedLayoutLazyRoute._addFileChildren(
    AuthenticatedLayoutLazyRouteChildren,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '': typeof AuthenticatedLayoutLazyRouteWithChildren
  '/signin': typeof SigninIndexLazyRoute
  '/browse': typeof AuthenticatedLayoutBrowseIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '': typeof AuthenticatedLayoutLazyRouteWithChildren
  '/signin': typeof SigninIndexLazyRoute
  '/browse': typeof AuthenticatedLayoutBrowseIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/_authenticated-layout': typeof AuthenticatedLayoutLazyRouteWithChildren
  '/signin/': typeof SigninIndexLazyRoute
  '/_authenticated-layout/browse/': typeof AuthenticatedLayoutBrowseIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/signin' | '/browse'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/signin' | '/browse'
  id:
    | '__root__'
    | '/'
    | '/_authenticated-layout'
    | '/signin/'
    | '/_authenticated-layout/browse/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AuthenticatedLayoutLazyRoute: typeof AuthenticatedLayoutLazyRouteWithChildren
  SigninIndexLazyRoute: typeof SigninIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AuthenticatedLayoutLazyRoute: AuthenticatedLayoutLazyRouteWithChildren,
  SigninIndexLazyRoute: SigninIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated-layout",
        "/signin/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/_authenticated-layout": {
      "filePath": "_authenticated-layout.lazy.tsx",
      "children": [
        "/_authenticated-layout/browse/"
      ]
    },
    "/signin/": {
      "filePath": "signin/index.lazy.tsx"
    },
    "/_authenticated-layout/browse/": {
      "filePath": "_authenticated-layout/browse/index.lazy.tsx",
      "parent": "/_authenticated-layout"
    }
  }
}
ROUTE_MANIFEST_END */
